apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: {{ .Values.appName }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: "{{ .Values.appimage }}:{{ .Values.appVersion }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: {{ .Values.containerPort }}
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: {{ .Values.containerPort }}
        volumeMounts:
        - mountPath: {{ .Values.containerMountPath }}
          name: {{ .Values.volumeName }}
        resources:
          limits:
            memory: 256Mi
            cpu: 125m
          requests:
            cpu: 70m
            memory: 200Mi
      volumes:
      - name: {{ .Values.volumeName }}
        emptyDir: {}