appName: paymentservice
appimage: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
appVersion: v0.10.4
containerPort: 50051
containerEnvVars:
  - name: PORT
    value: "50051"
  - name: DISABLE_PROFILER
    value: "1"

serviceType: ClusterIP
servicePort: 50051